# Generated by Django 3.0.8 on 2020-07-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='letters',
            field=models.CharField(default='', max_length=26),
        ),
    ]
