# Generated by Django 3.0.8 on 2020-07-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200730_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-joined']},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['game']},
        ),
    ]
